services:
  lapi:
    restart: always
    build:
        context: .
    ports:
      - "127.0.0.1:80:80"
      - "127.0.1.1:80:80"
    volumes:
      - "/dev/shm:/dev/shm"
      - ".:/var/www/html"
      - "/tmp:/tmp"
      - "/var/tmp:/var/tmp"
      - "./msmtprc:/etc/msmtprc"
    tmpfs:
      - /var/cache
      - /var/log
      - /var/lib/apt
      - /var/run
      - /var/spool
    hostname: lapihost
    dns:
      - 1.1.1.1
      - 8.8.8.8
    networks:
      - webnet
networks:
  webnet:
    driver: bridge
