services:
  lapi:
    restart: always
    build:
        context: .
        shm_size: 2g
    ports:
      - "80:80"
    volumes:
      - ".:/var/www/html"
      - "/tmp:/tmp"
      - "/var/tmp:/var/tmp"
    tmpfs:
      - /var/cache
      - /var/log
      - /var/lib/apt
      - /var/run
      - /var/spool
    hostname: lapihost
    dns:
      - 1.1.1.1
      - 8.8.8.8
